### ISSUE TITLE
Error using `com.mysql.jdbc.driver`

### ISSUE THREAD

**Issue by mrmechko** [tototoshi/sbt-slick-codegen#1]
Without the `sbt-slick-codegen` plugin, my code is able to connect to my `SQL` database with the `com.mysql.jdbc.driver`.  However, when running the `slickCodegen` task, I get the following error:

```
[info] Generate source code with slick-codegen: url=jdbc:mysql://localhost:3306/wordnet31, user=root
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at slick.jdbc.DriverBasedJdbcDataSource$class.registerDriver(JdbcDataSource.scala:59)
	at slick.jdbc.DriverJdbcDataSource.registerDriver(JdbcDataSource.scala:72)
	at slick.jdbc.DriverJdbcDataSource.<init>(JdbcDataSource.scala:78)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef$class.forURL(JdbcBackend.scala:101)
	at slick.jdbc.JdbcBackend$$anon$3.forURL(JdbcBackend.scala:33)
	at com.github.tototoshi.sbt.slick.CodegenPlugin$.com$github$tototoshi$sbt$slick$CodegenPlugin$$gen(CodegenPlugin.scala:63)
	at com.github.tototoshi.sbt.slick.CodegenPlugin$$anonfun$slickCodegenSettings$11.apply(CodegenPlugin.scala:97)
	at com.github.tototoshi.sbt.slick.CodegenPlugin$$anonfun$slickCodegenSettings$11.apply(CodegenPlugin.scala:93)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:slickCodegen) java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
```

Perhaps I specified the driver incorrectly? the string was copied directly from the existing `application.conf` file which contains the specification for connecting to the database.

Thanks

**Comment by hepin1989** [comment]
so do I,seems the classpath problem.

**Comment by hepin1989** [comment]
@mrmechko you could add the librarydependencies to the``` plugins.sbt ```file
